#!/usr/bin/env bash
# t-callers — THE behaviour-preservation proof for DRV-02.
#
# The five (caller, kind) pairs that existed before the shared adapter module — council's
# claude/codex/agy and shipyard's claude/codex — must still launch the agent with exactly the
# same ARGV. This file renders each pair through the REAL caller (council's `_write_launcher`,
# shipyard's `shipyard_agent_exec`), executes the rendered fragment with the agent CLIs faked to
# dump what they received, and compares that argv against fixtures/<pair>.argv.
#
# THE FIXTURES ARE FROZEN BASELINE, captured from the code as it stood BEFORE this change, at
#     57076cd8e97ff7a293eff1d71b3b0df52b94fefb   (the commit this branch forked from)
# by rendering `adapter_cmd`/`shipyard_agent_exec` with the same inputs and the same fake CLIs.
# That is the whole point: if both sides of the comparison were generated by the new module the
# test would be a tautology and would pass no matter what the migration broke.
#
# ARGV, not bytes. The rendered TEXT deliberately changed — one module has one data quoter
# (POSIX `'…'`, where council used `printf %q`) and one line style (where shipyard's codex was a
# single line) — so a byte-compare would be a compare of cosmetics. What must not change is what
# the agent process actually receives, which is what this measures. The rendered text is pinned
# separately, against goldens, in t-adapters.sh.
#
# This suite reaches into plugins/ where the other shared suites do not. It has to: half of what
# it proves is the CALLERS' mapping onto ADP_*, and a module-only test would still pass with
# council handing the launcher the wrong directories. shared/adapters/tests/ ships in no plugin,
# so nothing here crosses a packaging boundary.
if [ "${BASH_VERSINFO[0]:-0}" -lt 5 ] && [ -z "${TCAL_BASH_REEXEC:-}" ]; then
  for _c in /opt/homebrew/bin/bash /usr/local/bin/bash /usr/bin/bash bash; do
    _p=$(command -v "$_c" 2>/dev/null) || continue
    _v=$("$_p" -c 'echo ${BASH_VERSINFO[0]}' 2>/dev/null) || continue
    [ "${_v:-0}" -ge 5 ] && exec env TCAL_BASH_REEXEC=1 "$_p" "$0" "$@"
  done
  echo "t-callers: needs bash >= 5, this one is ${BASH_VERSION:-unknown}." >&2
  exit 70
fi

set -uo pipefail
export LC_ALL=C

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
ROOT="$(cd "$DIR/../../.." && pwd -P)"
FIX="$DIR/fixtures"
COUNCIL="$ROOT/plugins/council/skills/council"
SHIPYARD="$ROOT/plugins/shipyard/skills/shipyard"
[ -f "$COUNCIL/lib/up.sh" ] || { echo "t-callers: cannot find council's up.sh" >&2; exit 1; }
[ -f "$SHIPYARD/shipyard-agent.sh" ] || { echo "t-callers: cannot find shipyard-agent.sh" >&2; exit 1; }

TMP=$(mktemp -d "${TMPDIR:-/tmp}/adp-tc.XXXXXXXX") || exit 1
trap 'rm -rf "$TMP"' EXIT

CHECKS=0; FAILURES=0
ok() { # <label> <expected> <actual>
  CHECKS=$((CHECKS + 1))
  if [ "$2" = "$3" ]; then printf '  ok   %s\n' "$1"
  else printf '  FAIL %s\n' "$1"; diff -u <(printf '%s\n' "$2") <(printf '%s\n' "$3") | sed 's/^/         /'; FAILURES=$((FAILURES + 1)); fi
}

# --- the fixture inputs, identical to the ones the baseline was captured with ---------------
# Deliberately awkward: a space and a single quote in paths, so the quoting change is exercised
# for real; and a protocol file with non-trivial content, so a `$(cat …)` that got quoted away
# cannot pass — an empty protocol would compare equal either way.
FX="$TMP/fx"
ROOM="$FX/ro om"; SKILL_ARG="$FX/sk'ill"; PROTO="$FX/pro to.md"; WORKTREE="$FX/work tree"
mkdir -p "$ROOM/state" "$SKILL_ARG" "$WORKTREE"
cat >"$PROTO" <<'EOP'
PROTOCOL LINE ONE $notavar `notacmd`
PROTOCOL LINE TWO
EOP

BIN="$TMP/bin"; mkdir -p "$BIN"
for b in claude codex agy; do
  cat >"$BIN/$b" <<'EOF'
#!/usr/bin/env bash
printf '<<CMD>>\n%s\n<<END>>\n' "$(basename "$0")"
for a in "$@"; do printf '<<ARG>>\n%s\n<<END>>\n' "$a"; done
EOF
  chmod +x "$BIN/$b"
done

# Render a fragment, run it with the fakes, and normalise the fixture root out of the result.
argv_of() { # fragment on stdin
  local frag="$TMP/frag.sh"; cat >"$frag"
  ( PATH="$BIN:$PATH" bash "$frag" ) | sed "s#$FX#@FX@#g"
}

# --- council ------------------------------------------------------------------------------
# `_write_launcher <room> <peer> <kind> <cwd>` writes an executable launcher into the room; the
# first three lines are council's own preamble (shebang, exports, cd), and the exec line is what
# the adapter contributes. The preamble is asserted separately below.
SKILL="$SKILL_ARG"          # up.sh reads $SKILL, and council grants it to every participant
# shellcheck source=/dev/null
. "$COUNCIL/lib/up.sh"

council_argv() { # <kind>
  local kind="$1"
  cp "$PROTO" "$ROOM/protocol-alice.md"
  _write_launcher "$ROOM" alice "$kind" "$WORKTREE" || { echo "_write_launcher failed" >&2; return 1; }
  tail -n +4 "$ROOM/state/launch-alice.sh" | argv_of
}

printf '\n── council: the launched argv is unchanged ──\n'
for kind in claude codex agy; do
  ok "council/$kind launches the same agent process" \
    "$(cat "$FIX/council-$kind.argv")" "$(council_argv "$kind")"
done

printf '\n── council: the launcher preamble is unchanged ──\n'
_write_launcher "$ROOM" alice claude "$WORKTREE"
ok "the launcher still exports the room and the seat, and cds" \
  "#!/usr/bin/env bash
export COUNCIL_ROOM=@FX@/ro\\ om COUNCIL_ME=alice
cd @FX@/work\\ tree || exit 1" \
  "$(head -3 "$ROOM/state/launch-alice.sh" | sed "s#$FX#@FX@#g")"
ok "the launcher is executable" yes \
  "$([ -x "$ROOM/state/launch-alice.sh" ] && echo yes || echo no)"

printf '\n── council: the ADP_* knobs do not leak between seats ──\n'
# _write_launcher sets them in a subshell. A leak would make the NEXT seat inherit the previous
# kind's protocol path or approval, which is invisible until two kinds share a room.
leaked=""
for v in ADP_PROMPT ADP_PROTOCOL ADP_DIRS ADP_CWD ADP_NAME ADP_EFFORT ADP_APPROVAL; do
  [ -n "${!v:-}" ] && leaked="$leaked $v"
done
ok "no ADP_* variable survives _write_launcher" "" "$leaked"

printf '\n── and nothing leaks IN from the environment either ──\n'
# The other direction, which matters more: `adp_cmd` reads its inputs from the environment, so an
# exported ADP_* in whatever shell ran the supervisor would be rendered into a real launcher. The
# pre-change adapters took positional arguments and were immune by construction, so this is the
# one place the unification could have widened an agent's reach. Render every pair again with all
# seven knobs exported to sentinels and require the SAME frozen argv.
export ADP_PROMPT=INJECTED-PROMPT ADP_PROTOCOL=/INJECTED/PROTO ADP_DIRS=/INJECTED/DIR \
       ADP_CWD=/INJECTED/CWD ADP_NAME=INJECTED-NAME ADP_EFFORT=INJECTED-EFFORT ADP_APPROVAL=full
for kind in claude codex agy; do
  ok "council/$kind ignores an inherited ADP_*" \
    "$(cat "$FIX/council-$kind.argv")" "$(council_argv "$kind")"
done
unset ADP_PROMPT ADP_PROTOCOL ADP_DIRS ADP_CWD ADP_NAME ADP_EFFORT ADP_APPROVAL

printf '\n── council: an unknown kind is refused, and nothing is written ──\n'
rm -f "$ROOM/state/launch-bob.sh"
rc=0; _write_launcher "$ROOM" bob nonesuch "$WORKTREE" >/dev/null 2>&1 || rc=$?
ok "_write_launcher refuses a kind the module does not know" 1 "$rc"
ok "and leaves no launcher behind" no \
  "$([ -e "$ROOM/state/launch-bob.sh" ] && echo yes || echo no)"
# `ls -A`, NOT `ls`: the temp file is `.launch-<peer>.$$`, and plain `ls` never lists a dotfile,
# so the same grep over `ls` output matched nothing whatever the directory held — the assertion
# printed ok on precisely the state it exists to reject.
ok "and leaves no temp file behind" "" "$(ls -A "$ROOM/state" | grep '^\.launch-bob' || true)"

printf '\n── council: adding a kind touches no caller (DRV-02 acceptance) ──\n'
# The proof that council enumerates no kinds of its own: teach the module a fourth kind by
# redefining its API in this shell — exactly what a new `case` label in the module would do —
# and drive council's real _write_launcher with it, with NO edit to up.sh.
adp_known()         { case "${1:-}" in agy|claude|codex|stub) return 0 ;; *) return 1 ;; esac; }
adp_kinds()         { printf '%s\n' agy claude codex stub; }
adp_protocol_mode() { case "${1:-}" in stub) printf 'reference' ;; claude) printf 'system-prompt' ;;
                                       agy) printf 'inline' ;; codex) printf 'reference' ;; *) return 1 ;; esac; }
adp_cmd()           { [ "${1:-}" = stub ] || return 1
                      printf 'exec stub %s\n' "$(_adp_shq "${ADP_PROMPT:-}")"; }
rc=0; _write_launcher "$ROOM" carol stub "$WORKTREE" >/dev/null 2>&1 || rc=$?
ok "council launches a kind it has never heard of" 0 "$rc"
ok "and words the greeting from the kind's protocol MODE, not its name" \
  "exec stub 'Read @FX@/ro om/protocol-carol.md and follow it literally. Begin.'" \
  "$(tail -1 "$ROOM/state/launch-carol.sh" | sed "s#$FX#@FX@#g")"
# Put the real module back before anything else uses it.
# shellcheck source=../agent-adapters.sh
. "$DIR/../agent-adapters.sh"

# --- shipyard -----------------------------------------------------------------------------
printf '\n── shipyard: the launched argv is unchanged ──\n'
# shipyard-agent.sh sources the module beside it; nothing else in shipyard-lib is needed here.
# shellcheck source=/dev/null
. "$SHIPYARD/shipyard-agent.sh"

ok "shipyard/claude launches the same agent process" \
  "$(cat "$FIX/shipyard-claude.argv")" \
  "$(shipyard_agent_exec claude ship-42 "$WORKTREE" "$PROTO" '/ship #42' | argv_of)"
ok "shipyard/codex launches the same agent process" \
  "$(cat "$FIX/shipyard-codex.argv")" \
  "$(shipyard_agent_exec codex ship-42 "$WORKTREE" "$PROTO" '$ship #42' | argv_of)"

# The inbound direction again, for shipyard. `ADP_DIRS` is the sharp one: a leaked value becomes
# an extra `--add-dir` on a child that already runs with approvals off.
export ADP_PROMPT=INJECTED-PROMPT ADP_PROTOCOL=/INJECTED/PROTO ADP_DIRS=/INJECTED/DIR \
       ADP_CWD=/INJECTED/CWD ADP_NAME=INJECTED-NAME ADP_EFFORT=INJECTED-EFFORT ADP_APPROVAL=sandboxed
ok "shipyard/claude ignores an inherited ADP_*" \
  "$(cat "$FIX/shipyard-claude.argv")" \
  "$(shipyard_agent_exec claude ship-42 "$WORKTREE" "$PROTO" '/ship #42' | argv_of)"
ok "shipyard/codex ignores an inherited ADP_*" \
  "$(cat "$FIX/shipyard-codex.argv")" \
  "$(shipyard_agent_exec codex ship-42 "$WORKTREE" "$PROTO" '$ship #42' | argv_of)"
unset ADP_PROMPT ADP_PROTOCOL ADP_DIRS ADP_CWD ADP_NAME ADP_EFFORT ADP_APPROVAL

printf '\n── shipyard: the admission set is ITS OWN, not the module one ──\n'
# The module knows `agy` because council runs it. shipyard cannot supervise it, so it must not
# become launchable here just because the shared module learned how to start it.
ok "the module knows agy"                0 "$(adp_known agy; echo $?)"
ok "shipyard does not admit agy"         1 "$(shipyard_agent_admits agy; echo $?)"
ok "SHIPYARD_AGENT=agy resolves invalid" invalid "$(SHIPYARD_AGENT=agy shipyard_agent)"
ok "SHIPYARD_AGENT=agy is refused"       1 "$(SHIPYARD_AGENT=agy shipyard_agent_check >/dev/null 2>&1; echo $?)"
agy_msg=$(SHIPYARD_AGENT=agy shipyard_agent_check 2>&1 >/dev/null | head -1)
case "$agy_msg" in *SHIPYARD_AGENT*) ok "the refusal names the knob the operator set" yes yes ;;
                   *)                ok "the refusal names the knob the operator set" yes "no: [$agy_msg]" ;; esac
ok "shipyard_agent_exec refuses agy"     1 "$(shipyard_agent_exec agy n "$WORKTREE" "$PROTO" p >/dev/null 2>&1; echo $?)"
ok "and renders nothing for it"          "" "$(shipyard_agent_exec agy n "$WORKTREE" "$PROTO" p 2>/dev/null)"
ok "shipyard_skill_ref refuses agy"      1 "$(shipyard_skill_ref agy >/dev/null 2>&1; echo $?)"
ok "shipyard_self_ref refuses agy"       1 "$(shipyard_self_ref agy >/dev/null 2>&1; echo $?)"

printf '\n── approval: shipyard stays full, council stays sandboxed ──\n'
# The one place a behaviour-preserving refactor could silently change a security posture: the
# two callers need different freedom, and unifying them must not level it in either direction.
sy_codex=$(shipyard_agent_exec codex ship-42 "$WORKTREE" "$PROTO" '$ship #42' | head -1)
case "$sy_codex" in *--approve-for-me*) ok "shipyard's codex still runs with approvals off" yes yes ;;
                    *)                  ok "shipyard's codex still runs with approvals off" yes "no: [$sy_codex]" ;; esac
case "$sy_codex" in *workspace-write*) ok "and was not downgraded to the sandbox" yes "no: [$sy_codex]" ;;
                    *)                 ok "and was not downgraded to the sandbox" yes yes ;; esac
co_codex=$(council_argv codex)
case "$co_codex" in *workspace-write*) ok "council's codex still keeps the sandbox on" yes yes ;;
                    *)                 ok "council's codex still keeps the sandbox on" yes "no" ;; esac
case "$co_codex" in *approve-for-me*) ok "and was not widened to full approval" yes "no" ;;
                    *)                ok "and was not widened to full approval" yes yes ;; esac

printf '\n'
if [ "$FAILURES" -eq 0 ]; then echo "t-callers PASS ($CHECKS checks)"; else echo "t-callers FAIL ($FAILURES/$CHECKS)"; exit 1; fi
